### ISSUE TITLE
sessionID

### ISSUE THREAD

**Issue by ledahu** [selective-php/csrf#13]
Hi

im failing to implement the csrf in the odan skeleton with twig 

first :

`        // Set session id
        // The session must be started before you can get the session id
        $csrf->setSessionId(session_id());`

error session id not found (yes session is started)
and in the symfony/session, this is setId($id) 

any help ? 

then,even if i succeed to register csrf_token as a global in twig, i dont have any auto-populate hidden field in postform

and i dont understand how to route if taken veriification fail . 

May you can add the csrf middle in the odan skeleton (or the slimphp/csrf because composer say that this selective/csrf is abandonned so ....) 

thank you

Annexe 
`return function (App $app) {
    // Parse json, form data and xml
    $app->addBodyParsingMiddleware();

    $app->add(ValidationExceptionMiddleware::class);
    $app->add(SessionMiddleware::class);
    $app->add(CsrfMiddleware::class);
    $app->add(UrlGeneratorMiddleware::class);

    $app->addRoutingMiddleware();

    $app->add(TwigMiddleware::class);
    $app->add(BasePathMiddleware::class);
    $app->add(ErrorMiddleware::class);
};`

**Comment by odan** [comment]
First thing is, I deprecated this component because there were not much interest / downloads.

Second: There is already another good CSRF library for Slim [slim/slim-csrf](https://github.com/slimphp/Slim-Csrf). 

The 3. point is: Since PHP 7.3+ it's possible to send [SameSite cookies](https://web.dev/samesite-cookies-explained). This makes CSRF prevention techniques obsolete. Further details can be found here: [Sending SameSite cookies in PHP](https://gist.github.com/selective/87d16795f368c48757a1b08da5bd9899)

Now to your question.

>  The session must be started before you can get the session id $csrf->setSessionId(session_id());

When you use `session_id()` directly make sure to add the Session middleware like documented here:

https://github.com/selective-php/csrf#slim-4-integration

When you use a component, like Symfony Session, then you have to invoke the start method of the session instance like this: https://github.com/odan/slim4-skeleton/blob/master/src/Middleware/SessionMiddleware.php

> May you can add the csrf middle in the odan skeleton (or the slimphp/csrf because composer say that this selective/csrf is abandonned so ....)

I think SameSite cookies will make CSRF obsolete in the long run. Therefore I cannot and do not want to add (and support) it to the skeleton.

Please try to install the [slim/slim-csrf](https://github.com/slimphp/Slim-Csrf) component instead.

**Comment by ledahu** [comment]
HI

im stuck with slim/csrf ... :( i don't understand why the session is not started ... just why

i added this in my container :



Guard::class =>function ( ResponseFactoryInterface $responseFactory) {
    return new Guard($responseFactory);
},

CsrfMiddleware::class => function (ContainerInterface $container) {
    $guard=$container->get(Guard::class);
    return new CsrfMiddleware($guard);
},



and in my middleware.php


$app->add(SessionMiddleware::class);
$app->add(CsrfMiddleware::class);


and i get

Message: Invalid CSRF storage. Use session_start() before instantiating the Guard middleware or provide array storage.
File: C:\wamp64\www\personaroom\vendor\slim\csrf\src\Guard.php
Line: 141


any idea ? Because all exemple i find are MVC and old way to do things


Thank you

**Comment by ledahu** [comment]
pfff... im stupide : just have to inverse 

$app->add(CsrfMiddleware::class);

$app->add(SessionMiddleware::class);

Solved.
